--INSERT DATA

USE BeautyStudios
GO

INSERT INTO dbo.Studio (studio_name, city, address, phone_number, email) VALUES ('Best Haircut', 'Warszawa', 'Puławska 15', '6041258798', 'salon@wp.pl')
INSERT INTO dbo.Studio (studio_name, city, address, phone_number, email) VALUES ('4You', 'Radom', 'Belgradzka 1', '562369874', 'salon2@wp.pl')
INSERT INTO dbo.Studio (studio_name, city, address, phone_number, email) VALUES ('Ala', 'Piła', 'Wolna 3', '587965478', 'salon3@wp.pl')
INSERT INTO dbo.Studio (studio_name, city, address, phone_number, email) VALUES ('Ola', 'Piła', 'Polna 4', '875698523', 'salon4@wp.pl')
INSERT INTO dbo.Studio (studio_name, city, address, phone_number, email) VALUES ('Ela', 'Gdańsk', 'Rolna 98', '632587958', 'salon5@wp.pl')
INSERT INTO dbo.Studio (studio_name, city, address, phone_number, email) VALUES ('Quick', 'Gdańsk', 'Główna 7', '444666666', 'salon6@wp.pl')
INSERT INTO dbo.Studio (studio_name, city, address, phone_number, email) VALUES ('Quick4You', 'Gdańsk', 'Główna 45', '600001002', 'salon7@wp.pl')
INSERT INTO dbo.Studio (studio_name, city, address, phone_number, email) VALUES ('Best', 'Katowice', 'Francuska 3', '600001003', 'salon8@wp.pl')
INSERT INTO dbo.Studio (studio_name, city, address, phone_number, email) VALUES ('Yours', 'Katowice', 'Korfantego 4', '600001004', 'salon9@wp.pl')
INSERT INTO dbo.Studio (studio_name, city, address, phone_number, email) VALUES ('Haircut', 'Katowice', 'Gliwicka 22', '600001005', 'salon10@wp.pl')
INSERT INTO dbo.Studio (studio_name, city, address, phone_number, email) VALUES ('New', 'Katowice', 'Chorzowska 45', '600001006', 'salon11@wp.pl')

INSERT INTO dbo.Treatment (treatment_name, price) VALUES ('Strzyżenie męskie', 50)
INSERT INTO dbo.Treatment (treatment_name, price) VALUES ('Strzyżenie męskie maszynka', 30)
INSERT INTO dbo.Treatment (treatment_name, price) VALUES ('Strzyżenie i trymowanie brody', 80)
INSERT INTO dbo.Treatment (treatment_name, price) VALUES ('Strzyżenie damskie włosy krótkie', 80)
INSERT INTO dbo.Treatment (treatment_name, price) VALUES ('Strzyżenie damskie włosy średnie', 90)
INSERT INTO dbo.Treatment (treatment_name, price) VALUES ('Strzyżenie damskie włosy długie', 100)
INSERT INTO dbo.Treatment (treatment_name, price) VALUES ('Modelowanie damskie włosy krótkie', 60)
INSERT INTO dbo.Treatment (treatment_name, price) VALUES ('Modelowanie damskie włosy średnie', 70)
INSERT INTO dbo.Treatment (treatment_name, price) VALUES ('Modelowanie damskie włosy długie', 80)
INSERT INTO dbo.Treatment (treatment_name, price) VALUES ('Koloryzacja', 200)
INSERT INTO dbo.Treatment (treatment_name, price) VALUES ('Baleyage', 250)

INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Adam', 'Abacki', 'Warszawa', 'Puławska 1', '123456789', 'adam@wp.pl', 1)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Ola', 'Abacka', 'Warszawa', 'Puławska 1', '5555588878', 'ola@wp.pl', 1)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Anna', 'Wolna', 'Radom', 'Długa', '58965588852', 'anan@wp.pl', 2)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Marek', 'Dobry', 'Warszawa', 'Puławska 1', '123456789', 'fryzjer@wp.pl', 3)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Michał', 'Babacki', 'Katowice', 'Puławska 1', '123456789', 'fryzjer@wp.pl', 4)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Jola', 'Sama', 'Warszawa', 'Puławska 1', '123456789', 'fryzjer@wp.pl', 5)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Magda', 'Cabacka', 'Warszawa', 'Dobra 1', '123456789', 'fryzjer@wp.pl', 6)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Hanna', 'Abacki', 'Gdańsk', 'Główna 1', '123456789', 'fryzjer@wp.pl', 8)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Jan', 'Szybki', 'Warszawa', 'Nowa 1', '123456789', 'fryzjer@wp.pl', 10)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Marcin', 'Kowalski', 'Warszawa', 'Szybka 1', '123456789', 'fryzjer@wp.pl', 11)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Helena', 'Kowalska', 'Warszawa', 'Prosta 1', '123456789', 'fryzjer@wp.pl', 10)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Zuza', 'Nowak', 'Warszawa', 'Główna 1', '123456789', 'fryzjer@wp.pl', 9)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Wojciech', 'Nowacki', 'Warszawa', 'Polska 1', '123456789', 'fryzjer@wp.pl', 9)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Paweł', 'Nowakowski', 'Warszawa', 'Grecka 1', '123456789', 'fryzjer@wp.pl', 9)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Piotr', 'Nowy', 'Warszawa', 'Krótka 1', '123456789', 'fryzjer@wp.pl', 3)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Henryka', 'Kowal', 'Warszawa', 'Puławska 1', '123456789', 'fryzjer@wp.pl', 5)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Anna', 'Kowal', 'Warszawa', 'Puławska 1', '123456789', 'fryzjer@wp.pl', 8)
INSERT INTO dbo.Employee (first_name, last_name, city, address, phone_number, email, studio_id) VALUES ('Helena', 'Abacka', 'Warszawa', 'Puławska 1', '123456789', 'fryzjer@wp.pl', 1)

INSERT INTO dbo.Customer (first_name, last_name, phone_number) VALUES ('Marcin', 'Kowalski', '1236559525')
INSERT INTO dbo.Customer (first_name, last_name, phone_number) VALUES ('Anna', 'Kowalska', '1236559525')
INSERT INTO dbo.Customer (first_name, last_name, phone_number) VALUES ('Mariola', 'Polska', '43345344')
INSERT INTO dbo.Customer (first_name, last_name, phone_number) VALUES ('Helena', 'Nowak', '5432421321')
INSERT INTO dbo.Customer (first_name, last_name, phone_number) VALUES ('Włodzimierz', 'Abacki', '232332232')
INSERT INTO dbo.Customer (first_name, last_name, phone_number) VALUES ('Artur', 'Wolny', '323232')
INSERT INTO dbo.Customer (first_name, last_name, phone_number) VALUES ('Joanna', 'Wolny', '323232')

INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (1, '2020-10-20', '10:00', 1)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id, customer_id) VALUES (2, '2020-10-19', '11:00', 2, 2)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id, customer_id) VALUES (3, '2020-10-18', '12:00', 3, 3)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id, customer_id) VALUES (4, '2020-10-15', '13:00', 5, 4)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id, customer_id) VALUES (5, '2020-10-01', '14:00', 11, 5)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id, customer_id) VALUES (6, '2020-10-02', '14:00', 11, 6)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id, customer_id) VALUES (7, '2020-10-05', '15:00', 5, 7)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id, customer_id) VALUES (8, '2020-10-19', '16:00', 7, 8)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (9, '2020-10-16', '10:00', 2)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (10, '2020-10-19', '10:00', 3)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id, customer_id) VALUES (11, '2020-10-18', '12:00', 9, 1)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (12, '2020-10-09', '14:00', 7)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (3, '2020-10-19', '13:00', 7)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (2, '2020-10-05', '16:00', 8)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (1, '2020-10-12', '10:00', 3)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (3, '2020-10-19', '15:00', 1)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (7, '2020-10-13', '10:00', 2)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (5, '2020-10-19', '15:00', 4)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (3, '2020-10-15', '14:00', 6)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (9, '2020-10-19', '13:00', 8)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (10, '2020-10-01', '12:00', 2)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (18, '2020-10-19', '11:00', 6)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (5, '2020-10-02', '10:00', 2)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (8, '2020-10-03', '14:00', 1)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (2, '2020-10-01', '16:00', 11)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (5, '2020-10-19', '13:00', 2)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (1, '2020-10-08', '12:00', 2)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (7, '2020-10-10', '11:00', 1)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (3, '2020-10-12', '11:00', 2)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (1, '2020-09-20', '10:00', 1)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id, customer_id) VALUES (2, '2020-09-19', '11:00', 2, 2)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id, customer_id) VALUES (3, '2020-09-18', '12:00', 3, 3)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id, customer_id) VALUES (4, '2020-09-15', '13:00', 5, 4)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id, customer_id) VALUES (5, '2020-09-01', '14:00', 11, 5)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id, customer_id) VALUES (6, '2020-09-02', '14:00', 11, 6)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id, customer_id) VALUES (7, '2020-09-05', '15:00', 5, 7)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id, customer_id) VALUES (8, '2020-09-19', '16:00', 7, 8)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (9, '2020-09-16', '10:00', 2)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (10, '2020-09-19', '10:00', 3)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id, customer_id) VALUES (11, '2020-09-18', '12:00', 9, 1)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (12, '2020-09-09', '14:00', 7)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (3, '2020-09-19', '13:00', 7)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (2, '2020-09-05', '16:00', 8)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (1, '2020-09-12', '10:00', 3)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (3, '2020-09-19', '15:00', 1)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (7, '2020-09-13', '10:00', 2)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (5, '2020-09-19', '15:00', 4)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (3, '2020-09-15', '14:00', 6)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (9, '2020-09-19', '13:00', 8)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (10, '2020-09-01', '12:00', 2)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (18, '2020-09-19', '11:00', 6)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (5, '2020-09-02', '10:00', 2)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (8, '2020-09-03', '14:00', 1)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (2, '2020-09-01', '16:00', 11)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (5, '2020-09-19', '13:00', 2)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (1, '2020-09-08', '12:00', 2)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (7, '2020-09-10', '11:00', 1)
INSERT INTO dbo.Visit (employee_id, visit_date, visit_time, treatment_id) VALUES (3, '2020-09-12', '11:00', 2)
